USE test;

CREATE TABLE IF NOT EXISTS USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    height FLOAT,
    weight FLOAT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS EXERCISE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    exercise_type VARCHAR(255) NOT NULL,
    set_num INT NOT NULL,
    reps INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
)

-- email 컬럼 추가
ALTER TABLE USER ADD COLUMN email VARCHAR(255) NOT NULL;

-- email 컬럼 유니크 제약 추가
ALTER TABLE USER ADD CONSTRAINT unique_email UNIQUE (email);